/** Homepage copy is paired so both locales share the same composition and links. */
export const homeCopy = {
  ro: {
    servicesLabel: "Expertiză conectată",
    servicesTitle: "Fiecare provocare IT.\nO direcție de lucru.",
    servicesIntro:
      "Pentru organizații cu nevoi IT interconectate. Reunim infrastructura, securitatea, software-ul și operarea într-o colaborare coordonată.",
    services: [
      {
        title: "Infrastructură & Cloud",
        body: "O arhitectură pregătită pentru ceea ce urmează. De la data center la medii private și hibride.",
        detail: "Arhitectură · Cloud · Continuitate",
        href: "/servicii/cloud",
      },
      {
        title: "Networking & Security",
        body: "Conectăm infrastructura și protejăm accesul, identitatea și informațiile organizației.",
        detail: "Rețea · Identitate · Protecție",
        href: "/servicii/securitate",
      },
      {
        title: "Software & Automatizare",
        body: "Aplicații care lucrează împreună. Dezvoltare custom, integrare și automatizarea proceselor.",
        detail: "Software custom · API · DevSecOps",
        href: "/servicii/software",
      },
      {
        title: "Servicii Gestionate",
        body: "O relație continuă pentru întregul mediu IT. Monitorizare, suport și îmbunătățiri, cu responsabilități agreate.",
        detail: "Monitorizare · Operare · Suport",
        href: "/servicii/managed",
      },
    ],
    stackLabel: "De la infrastructură la aplicații",
    stackTitle: "Piesele se schimbă.\nResponsabilitatea rămâne clară.",
    stackBody:
      "Echipa Smart Control răspunde direct de livrare și coordonează specialiștii și partenerii tehnologici necesari. Explorează nivelurile infrastructurii.",
    stackNote:
      "Nivelurile de serviciu și indicatorii sunt agreate contractual.",
    layers: [
      {
        code: "L4",
        name: "Aplicații & Automatizare",
        desc: "Software custom, API-uri și automatizare cu AI / LLM.",
        chips: [
          "Custom dev & API",
          "Modernizare aplicații",
          "Automatizare AI / LLM",
          "CI/CD & DevSecOps",
        ],
        href: "/servicii/software",
        linkLabel: "Software & Automatizare",
        aria: "Nivel L4 — Aplicații și Automatizare",
      },
      {
        code: "L3",
        name: "Platforme & Date",
        desc: "Virtualizare, cloud privat / hibrid, containere și storage.",
        chips: [
          "VMware · K8s / OpenShift",
          "Private / Hybrid Cloud",
          "Storage & backup",
          "Disaster Recovery",
        ],
        href: "/servicii/cloud",
        linkLabel: "Infrastructură & Cloud",
        aria: "Nivel L3 — Platforme și Date",
      },
      {
        code: "L2",
        name: "Rețea & Conectivitate",
        desc: "Core networking, SD-WAN și acces remote securizat.",
        chips: [
          "LAN / WAN core",
          "SD-WAN",
          "Acces remote securizat",
          "Load balancing",
        ],
        href: "/servicii/securitate",
        linkLabel: "Networking & Security",
        aria: "Nivel L2 — Rețea și Conectivitate",
      },
      {
        code: "L1",
        name: "Infrastructură fizică",
        desc: "Data center, compute, energie și cablare structurată.",
        chips: [
          "DC design & build",
          "Compute & storage",
          "Energie & cooling",
          "Cablare structurată",
        ],
        href: "/servicii/cloud",
        linkLabel: "Infrastructură & Cloud",
        aria: "Nivel L1 — Infrastructură fizică",
      },
    ],
    productsLabel: "Produse Smart Control",
    productsTitle: "Mai multă vizibilitate.\nAcces mai bine controlat.",
    productsIntro:
      "Două produse proprii, pentru monitorizarea mediilor IT și acces remote securizat.",
    products: [
      {
        name: "SEKNET",
        label: "Monitorizare & securitate",
        body: "O perspectivă comună asupra infrastructurii, evenimentelor și riscurilor. Pentru echipele care coordonează operațiunile și răspunsul.",
        href: "/solutii/seknet",
        steps: ["Infrastructură", "Evenimente", "Analiză"],
        caption: "Schemă conceptuală de monitorizare",
      },
      {
        name: "S-VPN",
        label: "Acces remote securizat",
        body: "Conectarea utilizatorilor la resursele organizației, cu acces securizat adaptat cerințelor mediului IT.",
        href: "/solutii/s-vpn",
        steps: ["Utilizator", "Acces securizat", "Resurse IT"],
        caption: "Schemă conceptuală de acces",
      },
    ],
    explore: "Explorează",
    partnersLabel: "Ecosistem tehnologic",
    partnersTitle: "Expertiza noastră.\nTehnologiile potrivite.",
    partnersBody:
      "Lucrăm cu parteneri tehnologici și selectăm componentele în funcție de cerințele proiectului.",
    contactLabel: "Să discutăm despre infrastructura ta",
    contactTitle: "Următorul pas începe\ncu întrebările potrivite.",
    contactBody:
      "Spune-ne ce vrei să îmbunătățești. Stabilim împreună scopul assessment-ului și pașii următori.",
  },
  en: {
    servicesLabel: "Connected expertise",
    servicesTitle: "Every IT challenge.\nA clear way forward.",
    servicesIntro:
      "For organisations with connected IT needs. We bring infrastructure, security, software and operations into one coordinated engagement.",
    services: [
      {
        title: "Infrastructure & Cloud",
        body: "An architecture ready for what comes next. From data centres to private and hybrid environments.",
        detail: "Architecture · Cloud · Continuity",
        href: "/servicii/cloud",
      },
      {
        title: "Networking & Security",
        body: "Connecting infrastructure and protecting access, identity and your organisation’s information.",
        detail: "Network · Identity · Protection",
        href: "/servicii/securitate",
      },
      {
        title: "Software & Automation",
        body: "Applications that work together. Custom development, integration and process automation.",
        detail: "Custom software · API · DevSecOps",
        href: "/servicii/software",
      },
      {
        title: "Managed Services",
        body: "The ongoing relationship across your IT environment. Monitoring, support and improvements with agreed responsibilities.",
        detail: "Monitoring · Operations · Support",
        href: "/servicii/managed",
      },
    ],
    stackLabel: "From infrastructure to applications",
    stackTitle: "The layers change.\nAccountability stays clear.",
    stackBody:
      "The Smart Control team remains directly accountable for delivery and coordinates the specialists and technology partners each project requires. Explore the infrastructure layers.",
    stackNote: "Service levels and indicators are agreed contractually.",
    layers: [
      {
        code: "L4",
        name: "Applications & Automation",
        desc: "Custom software, APIs and AI / LLM automation.",
        chips: [
          "Custom dev & API",
          "App modernisation",
          "AI / LLM automation",
          "CI/CD & DevSecOps",
        ],
        href: "/servicii/software",
        linkLabel: "Software & Automation",
        aria: "Layer L4 — Applications and Automation",
      },
      {
        code: "L3",
        name: "Platforms & Data",
        desc: "Virtualisation, private / hybrid cloud, containers and storage.",
        chips: [
          "VMware · K8s / OpenShift",
          "Private / Hybrid Cloud",
          "Storage & backup",
          "Disaster Recovery",
        ],
        href: "/servicii/cloud",
        linkLabel: "Infrastructure & Cloud",
        aria: "Layer L3 — Platforms and Data",
      },
      {
        code: "L2",
        name: "Network & Connectivity",
        desc: "Core networking, SD-WAN and secure remote access.",
        chips: [
          "LAN / WAN core",
          "SD-WAN",
          "Secure remote access",
          "Load balancing",
        ],
        href: "/servicii/securitate",
        linkLabel: "Networking & Security",
        aria: "Layer L2 — Network and Connectivity",
      },
      {
        code: "L1",
        name: "Physical infrastructure",
        desc: "Data centre, compute, power and structured cabling.",
        chips: [
          "DC design & build",
          "Compute & storage",
          "Power & cooling",
          "Structured cabling",
        ],
        href: "/servicii/cloud",
        linkLabel: "Infrastructure & Cloud",
        aria: "Layer L1 — Physical infrastructure",
      },
    ],
    productsLabel: "Smart Control products",
    productsTitle: "More visibility.\nBetter controlled access.",
    productsIntro:
      "Two proprietary products for monitoring IT environments and securing remote access.",
    products: [
      {
        name: "SEKNET",
        label: "Monitoring & security",
        body: "A shared perspective on infrastructure, events and risks. For teams coordinating operations and response.",
        href: "/solutii/seknet",
        steps: ["Infrastructure", "Events", "Analysis"],
        caption: "Conceptual monitoring diagram",
      },
      {
        name: "S-VPN",
        label: "Secure remote access",
        body: "Connecting users to organisational resources, with secure access adapted to the requirements of the IT environment.",
        href: "/solutii/s-vpn",
        steps: ["User", "Secure access", "IT resources"],
        caption: "Conceptual access diagram",
      },
    ],
    explore: "Explore",
    partnersLabel: "Technology ecosystem",
    partnersTitle: "Our expertise.\nThe right technologies.",
    partnersBody:
      "We work with technology partners and select components around each project’s requirements.",
    contactLabel: "Let’s talk about your infrastructure",
    contactTitle: "The next step starts\nwith the right questions.",
    contactBody:
      "Tell us what you want to improve. Together, we define the assessment scope and the next steps.",
  },
};
export const technologyPartners = [
  "Hitachi Vantara",
  "Commvault",
  "Fortinet",
  "Cisco",
  "Juniper",
  "Lenovo",
  "VMware",
  "Fujitsu",
  "Oracle",
  "Microsoft",
  "Palo Alto",
  "Hanasis",
  "IBM",
  "HPE",
  "DELL",
];
