/** Homepage copy is paired so both locales share the same composition and links. */
export const homeCopy = {
  ro: {
    servicesLabel: "Servicii IT",
    servicesTitle: "Ce putem face\npentru echipa ta",
    servicesIntro:
      "Un proiect poate include mai multe dintre aceste servicii. Le planificăm împreună, ținând cont de sistemele existente.",
    services: [
      {
        title: "Infrastructură & Cloud",
        body: "Proiectăm și modernizăm data center-e, infrastructuri on-premises și medii cloud private sau hibride.",
        detail: "Arhitectură · Cloud · Continuitate",
        href: "/servicii/cloud",
      },
      {
        title: "Networking & Security",
        body: "Configurăm rețele, administrăm accesul și implementăm măsuri de securitate pentru date și sisteme.",
        detail: "Rețea · Identitate · Protecție",
        href: "/servicii/securitate",
      },
      {
        title: "Software & Automatizare",
        body: "Dezvoltăm aplicații, integrăm sisteme și automatizăm procesele de lucru.",
        detail: "Software custom · API · DevSecOps",
        href: "/servicii/software",
      },
      {
        title: "Servicii Gestionate",
        body: "Monitorizăm și administrăm sistemele IT și preluăm solicitările de suport, conform serviciilor agreate.",
        detail: "Monitorizare · Operare · Suport",
        href: "/servicii/managed",
      },
    ],
    stackLabel: "De la infrastructură la aplicații",
    stackTitle: "Cum se leagă\nsistemele tale",
    stackBody:
      "Aplicațiile depind de platforme, rețea și infrastructura fizică. Selectează un nivel pentru a vedea serviciile aferente.",
    stackNote:
      "Nivelurile de serviciu și indicatorii sunt agreați contractual.",
    layers: [
      {
        code: "L4",
        name: "Aplicații & Automatizare",
        desc: "Software custom, API-uri și automatizarea proceselor.",
        chips: [
          "Custom dev & API",
          "Modernizare aplicații",
          "Automatizare AI / LLM",
          "CI/CD & DevSecOps",
        ],
        href: "/servicii/software",
        linkLabel: "Software & Automatizare",
        aria: "Nivel L4 — Aplicații și Automatizare",
      },
      {
        code: "L3",
        name: "Platforme & Date",
        desc: "Virtualizare, cloud privat / hibrid, containere și storage.",
        chips: [
          "VMware · K8s / OpenShift",
          "Private / Hybrid Cloud",
          "Storage & backup",
          "Disaster Recovery",
        ],
        href: "/servicii/cloud",
        linkLabel: "Infrastructură & Cloud",
        aria: "Nivel L3 — Platforme și Date",
      },
      {
        code: "L2",
        name: "Rețea & Conectivitate",
        desc: "Core networking, SD-WAN și acces remote securizat.",
        chips: [
          "LAN / WAN core",
          "SD-WAN",
          "Acces remote securizat",
          "Load balancing",
        ],
        href: "/servicii/securitate",
        linkLabel: "Networking & Security",
        aria: "Nivel L2 — Rețea și Conectivitate",
      },
      {
        code: "L1",
        name: "Infrastructură fizică",
        desc: "Data center, compute, energie și cablare structurată.",
        chips: [
          "DC design & build",
          "Compute & storage",
          "Energie & cooling",
          "Cablare structurată",
        ],
        href: "/servicii/cloud",
        linkLabel: "Infrastructură & Cloud",
        aria: "Nivel L1 — Infrastructură fizică",
      },
    ],
    productsLabel: "Produse Smart Control",
    productsTitle: "Monitorizare IT și\nacces remote",
    productsIntro:
      "SEKNET și S-VPN sunt produsele dezvoltate de Smart Control.",
    products: [
      {
        name: "SEKNET",
        label: "Monitorizare & securitate",
        body: "Monitorizează infrastructura și centralizează evenimentele pentru echipele de operațiuni și securitate.",
        href: "/solutii/seknet",
        steps: ["Infrastructură", "Evenimente", "Analiză"],
        caption: "Schemă conceptuală de monitorizare",
      },
      {
        name: "S-VPN",
        label: "Acces remote securizat",
        body: "Conectează utilizatorii la resursele companiei prin acces remote securizat, administrat de echipa IT.",
        href: "/solutii/s-vpn",
        steps: ["Utilizator", "Acces securizat", "Resurse IT"],
        caption: "Schemă conceptuală de acces",
      },
    ],
    explore: "Explorează",
    partnersLabel: "Tehnologii",
    partnersTitle: "Parteneri tehnologici",
    partnersBody:
      "Alegem tehnologiile în funcție de cerințele proiectului și de sistemele pe care le folosești deja.",
    contactLabel: "Contact",
    contactTitle: "Să discutăm despre\nnevoile tale IT",
    contactBody:
      "Spune-ne ce vrei să îmbunătățești. Stabilim împreună ce trebuie evaluat și cum putem ajuta.",
  },
  en: {
    servicesLabel: "IT services",
    servicesTitle: "How we can help\nyour team",
    servicesIntro:
      "A project can span several of these services. We plan the work together, taking your existing systems into account.",
    services: [
      {
        title: "Infrastructure & Cloud",
        body: "We design and modernise data centres, on-premises infrastructure and private or hybrid cloud environments.",
        detail: "Architecture · Cloud · Continuity",
        href: "/servicii/cloud",
      },
      {
        title: "Networking & Security",
        body: "We configure networks, manage access and implement security measures for data and systems.",
        detail: "Network · Identity · Protection",
        href: "/servicii/securitate",
      },
      {
        title: "Software & Automation",
        body: "We develop applications, integrate systems and automate business processes.",
        detail: "Custom software · API · DevSecOps",
        href: "/servicii/software",
      },
      {
        title: "Managed Services",
        body: "We monitor and manage IT systems and handle support requests under the agreed service scope.",
        detail: "Monitoring · Operations · Support",
        href: "/servicii/managed",
      },
    ],
    stackLabel: "From infrastructure to applications",
    stackTitle: "How your systems\nfit together",
    stackBody:
      "Applications depend on platforms, networks and physical infrastructure. Select a layer to see the related services.",
    stackNote: "Service levels and indicators are agreed contractually.",
    layers: [
      {
        code: "L4",
        name: "Applications & Automation",
        desc: "Custom software, APIs and process automation.",
        chips: [
          "Custom dev & API",
          "App modernisation",
          "AI / LLM automation",
          "CI/CD & DevSecOps",
        ],
        href: "/servicii/software",
        linkLabel: "Software & Automation",
        aria: "Layer L4 — Applications and Automation",
      },
      {
        code: "L3",
        name: "Platforms & Data",
        desc: "Virtualisation, private / hybrid cloud, containers and storage.",
        chips: [
          "VMware · K8s / OpenShift",
          "Private / Hybrid Cloud",
          "Storage & backup",
          "Disaster Recovery",
        ],
        href: "/servicii/cloud",
        linkLabel: "Infrastructure & Cloud",
        aria: "Layer L3 — Platforms and Data",
      },
      {
        code: "L2",
        name: "Network & Connectivity",
        desc: "Core networking, SD-WAN and secure remote access.",
        chips: [
          "LAN / WAN core",
          "SD-WAN",
          "Secure remote access",
          "Load balancing",
        ],
        href: "/servicii/securitate",
        linkLabel: "Networking & Security",
        aria: "Layer L2 — Network and Connectivity",
      },
      {
        code: "L1",
        name: "Physical infrastructure",
        desc: "Data centre, compute, power and structured cabling.",
        chips: [
          "DC design & build",
          "Compute & storage",
          "Power & cooling",
          "Structured cabling",
        ],
        href: "/servicii/cloud",
        linkLabel: "Infrastructure & Cloud",
        aria: "Layer L1 — Physical infrastructure",
      },
    ],
    productsLabel: "Smart Control products",
    productsTitle: "IT monitoring and\nremote access",
    productsIntro:
      "SEKNET and S-VPN are products developed by Smart Control.",
    products: [
      {
        name: "SEKNET",
        label: "Monitoring & security",
        body: "Monitor infrastructure and bring events together for operations and security teams.",
        href: "/solutii/seknet",
        steps: ["Infrastructure", "Events", "Analysis"],
        caption: "Conceptual monitoring diagram",
      },
      {
        name: "S-VPN",
        label: "Secure remote access",
        body: "Connect users to company resources through secure remote access managed by the IT team.",
        href: "/solutii/s-vpn",
        steps: ["User", "Secure access", "IT resources"],
        caption: "Conceptual access diagram",
      },
    ],
    explore: "Explore",
    partnersLabel: "Technology",
    partnersTitle: "Technology partners",
    partnersBody:
      "We choose technologies to suit the project requirements and the systems you already use.",
    contactLabel: "Contact",
    contactTitle: "Tell us about\nyour IT plans",
    contactBody:
      "Tell us what you want to improve. We will agree what needs assessing and how we can help.",
  },
};
export const technologyPartners = [
  "Hitachi Vantara",
  "Commvault",
  "Fortinet",
  "Cisco",
  "Juniper",
  "Lenovo",
  "VMware",
  "Fujitsu",
  "Oracle",
  "Microsoft",
  "Palo Alto",
  "Hanasis",
  "IBM",
  "HPE",
  "DELL",
];
